from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, ReplyKeyboardRemove


kb = ReplyKeyboardMarkup(resize_keyboard=True)
kb.add(KeyboardButton('/help'))
kb.add(KeyboardButton('zilliqa'))
kb.add(KeyboardButton('rockx'))
kb.add(KeyboardButton('ezil.me'))
kb.add(KeyboardButton('wave'))
kb.add(KeyboardButton('shardpool.io'))
kb.add(KeyboardButton('valkyrie2'))
kb.add(KeyboardButton('huobi staking'))
kb.add(KeyboardButton('zilliqa2'))
kb.add(KeyboardButton('moonlet.io'))
kb.add(KeyboardButton('bountyblok'))
kb.add(KeyboardButton('everstake.one'))
kb.add(KeyboardButton('nodamatics.com'))
kb.add(KeyboardButton('zilpay'))
kb.add(KeyboardButton('avely finance'))
kb.add(KeyboardButton('viewblock'))
kb.add(KeyboardButton('atomicwallet'))
kb.add(KeyboardButton('binance staking'))
kb.add(KeyboardButton('luganodes'))
kb.add(KeyboardButton('cex.io'))
kb.add(KeyboardButton('blox-sdk staking'))
kb.add(KeyboardButton('valkyrie investments'))
kb.add(KeyboardButton('ignite dao'))
kb.add(KeyboardButton('zillet'))
kb.add(KeyboardButton('staked'))
kb.add(KeyboardButton('kucoin'))
kb.add(KeyboardButton('hashquark'))
kb.add(KeyboardButton('stakin'))

