"""add repr

Revision ID: 05c1b84976a5
Revises: 947b1c0caa1b
Create Date: 2023-06-05 19:15:16.561306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c1b84976a5'
down_revision = '947b1c0caa1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
