"""add repr

Revision ID: 2763d2cc56e1
Revises: f003b455851b
Create Date: 2023-06-05 17:56:15.312340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2763d2cc56e1'
down_revision = 'f003b455851b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
