"""models

Revision ID: 3d5117601e0f
Revises: bb1ed00fd34f
Create Date: 2023-08-06 13:04:10.982355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5117601e0f'
down_revision = 'bb1ed00fd34f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blocks', ['block_id'])
    op.create_unique_constraint(None, 'nodes', ['node_id'])
    op.create_unique_constraint(None, 'records', ['record_id'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'records', type_='unique')
    op.drop_constraint(None, 'nodes', type_='unique')
    op.drop_constraint(None, 'blocks', type_='unique')
    # ### end Alembic commands ###
