"""add repr

Revision ID: 5dc28cca694c
Revises: 05c1b84976a5
Create Date: 2023-06-05 19:28:06.643939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc28cca694c'
down_revision = '05c1b84976a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
