"""add recodrs

Revision ID: 653867f3efd6
Revises: 80017bdbba38
Create Date: 2023-05-29 15:52:36.750513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653867f3efd6'
down_revision = '80017bdbba38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
