"""db creation

Revision ID: 80017bdbba38
Revises: 
Create Date: 2023-05-23 17:27:45.999429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80017bdbba38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('nodes_id', sa.Integer(), nullable=False),
    sa.Column('node_url', sa.String(), nullable=False),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nodes_id'),
    sa.UniqueConstraint('node_url'),
    sa.UniqueConstraint('nodes_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=False),
    sa.Column('reg_date', sa.Integer(), nullable=False),
    sa.Column('upd_date', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'user_telegram_id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_telegram_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users_nodes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.nodes_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_nodes')
    op.drop_table('users')
    op.drop_table('nodes')
    # ### end Alembic commands ###
