"""add repr

Revision ID: 947b1c0caa1b
Revises: 2763d2cc56e1
Create Date: 2023-06-05 18:59:02.599116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947b1c0caa1b'
down_revision = '2763d2cc56e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
