"""add repr

Revision ID: ba64859d0b61
Revises: 
Create Date: 2023-06-09 20:48:01.014470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba64859d0b61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('node_url', sa.String(), nullable=False),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('node_id'),
    sa.UniqueConstraint('node_id'),
    sa.UniqueConstraint('node_url')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=False),
    sa.Column('reg_date', sa.Integer(), nullable=False),
    sa.Column('upd_date', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'user_telegram_id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_telegram_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('current_ds_epoch', sa.Integer(), nullable=True),
    sa.Column('current_mini_epoch', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users_nodes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_nodes')
    op.drop_table('records')
    op.drop_table('users')
    op.drop_table('nodes')
    # ### end Alembic commands ###
