"""add get_all_records_from_db

Revision ID: f003b455851b
Revises: e0c6820fc543
Create Date: 2023-06-05 16:45:59.655730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f003b455851b'
down_revision = 'e0c6820fc543'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
