MAIN_NODE = 'https://api.zilliqa.com/'
URL_FOR_DELEGATES = 'https://ssn.zilpay.io/api'
MAX_NODE_TIMEOUT_SECOND = 10

MIN_DIFFERENCE_OF_BLOCKS = 1
MAX_DIFFERENCE_OF_BLOCKS = 10
PAUSE_BETWEEN_REQUESTS = 3

TRUST_COEFFICIENT = 50
