MAIN_NODE = 'https://api.zilliqa.com/'
MAX_NODE_TIMEOUT_SECOND = 5
MAX_DIFFERENCE_OF_BLOCKS = 2
MIN_DIFFERENCE_OF_BLOCKS = 1
MAX_RESPONSE_SECONDS = 8
AVERAGE_RESPONSE_SECONDS = 6
MIN_RESPONSE_SECONDS = 2
